# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'projectGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(793, 812)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabSwitcher = QtWidgets.QTabWidget(self.centralwidget)
        self.tabSwitcher.setGeometry(QtCore.QRect(0, 0, 791, 551))
        self.tabSwitcher.setObjectName("tabSwitcher")
        self.prediction = QtWidgets.QWidget()
        self.prediction.setObjectName("prediction")
        self.tabSwitcher.addTab(self.prediction, "")
        self.dataSet = QtWidgets.QWidget()
        self.dataSet.setObjectName("dataSet")
        self.downloadButton = QtWidgets.QPushButton(self.dataSet)
        self.downloadButton.setGeometry(QtCore.QRect(20, 150, 101, 23))
        self.downloadButton.setObjectName("downloadButton")
        self.progressBar = QtWidgets.QProgressBar(self.dataSet)
        self.progressBar.setEnabled(False)
        self.progressBar.setGeometry(QtCore.QRect(20, 180, 331, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(True)
        self.progressBar.setObjectName("progressBar")
        self.timeRemainingLabel = QtWidgets.QLabel(self.dataSet)
        self.timeRemainingLabel.setEnabled(False)
        self.timeRemainingLabel.setGeometry(QtCore.QRect(30, 210, 81, 16))
        self.timeRemainingLabel.setObjectName("timeRemainingLabel")
        self.timeRemaininCount = QtWidgets.QLabel(self.dataSet)
        self.timeRemaininCount.setGeometry(QtCore.QRect(120, 210, 141, 16))
        self.timeRemaininCount.setObjectName("timeRemaininCount")
        self.cancelButton = QtWidgets.QPushButton(self.dataSet)
        self.cancelButton.setEnabled(False)
        self.cancelButton.setGeometry(QtCore.QRect(210, 150, 101, 23))
        self.cancelButton.setObjectName("cancelButton")
        self.tabSwitcher.addTab(self.dataSet, "")
        self.viewDataset = QtWidgets.QWidget()
        self.viewDataset.setObjectName("viewDataset")
        self.tabSwitcher.addTab(self.viewDataset, "")
        self.training = QtWidgets.QWidget()
        self.training.setObjectName("training")
        self.tabSwitcher.addTab(self.training, "")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(10, 580, 771, 192))
        self.textBrowser.setObjectName("textBrowser")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 560, 81, 16))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 793, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabSwitcher.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tabSwitcher.setTabText(self.tabSwitcher.indexOf(self.prediction), _translate("MainWindow", "Prediction"))
        self.downloadButton.setText(_translate("MainWindow", "Begin Download"))
        self.timeRemainingLabel.setText(_translate("MainWindow", "Time Remaininig:"))
        self.timeRemaininCount.setText(_translate("MainWindow", "XX Minutes and XX Seconds"))
        self.cancelButton.setText(_translate("MainWindow", "Cancel Download"))
        self.tabSwitcher.setTabText(self.tabSwitcher.indexOf(self.dataSet), _translate("MainWindow", "DataSet"))
        self.tabSwitcher.setTabText(self.tabSwitcher.indexOf(self.viewDataset), _translate("MainWindow", "View DataSet"))
        self.tabSwitcher.setTabText(self.tabSwitcher.indexOf(self.training), _translate("MainWindow", "Training"))
        self.label.setText(_translate("MainWindow", "Program Status"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
